// Code generated by mockery v2.39.0. DO NOT EDIT.

package mocks

import (
	models "albums/internal/models"
	mock "github.com/stretchr/testify/mock"
)

type LoginService struct {
	mock.Mock
}

func (m *LoginService) JWTTokenGenerator(userID string) (string, error) {
	args := m.Called(userID)
	return args.String(0), args.Error(1)
}

func (m *LoginService) GetUserbyID(userID string) (models.Users, error) {
	args := m.Called(userID)
	return args.Get(0).(models.Users), args.Error(1)
}

func (m *LoginService) GetUserInfo(username string) (models.Users, error) {
	args := m.Called(username)
	return args.Get(0).(models.Users), args.Error(1)
}

func (m *LoginService) RegisterUser(username, password string) (models.Users, error) {
	args := m.Called(username, password)
	return args.Get(0).(models.Users), args.Error(1)
}

func (m *LoginService) ValidateCredentials(username, password string) (bool, uint, error) {
	args := m.Called(username, password)
	return args.Bool(0), uint(args.Int(1)), args.Error(2)
}
